(function(){function home(it
/**/) {
var out='<!doctype html><html lang="en"><head> <meta charset="utf-8"> <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge"><![endif]--> <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" /> <title>LanguageCast</title> <meta name="description" content="Improve a second language! Here you can with native speakers around the world."> <meta name="keywords" content="Free conversation class with native speakers"> <link rel="shortcut icon" href="assets/img/favicon.ico"> <link href=\'http://fonts.googleapis.com/css?family=Lato:100,300,400,700\' rel=\'stylesheet\' type=\'text/css\'> <link rel="stylesheet" href="assets/css/bootstrap.min.css" type="text/css" media="all" /> <link rel="stylesheet" href="assets/css/font-awesome.min.css" type="text/css" media="all" /> <link rel="stylesheet" href="assets/css/style.css" type="text/css" media="all" /> <link rel="stylesheet" href="//assets.ziggeo.com/css/ziggeo-betajs-player.min.css" /><script src="//assets.ziggeo.com/js/ziggeo-jquery-json2-betajs-player.min.js"></script><script>ZiggeoApi.token = "1d8e2dfa187b59324525ab3990c6cf81";</script></head><body id="landing-page"> <!-- Preloader --> <div id="mask"> <div id="loader"></div> </div> <header> <nav class="navigation navigation-header"> <div class="container"> <div class="navigation-brand"> <div class="brand-logo"><a href="index.html" class="logo"></a><span class="sr-only">LanguageCast</span> </div>  </div> <div class="navigation-navbar"> <ul class="navigation-bar navigation-bar-left"> <li class="active"><a href="#hero">Home</a></li> </ul> <ul class="navigation-bar navigation-bar-right"> <li><a href="register.html">Login</a></li> <li class="featured"><a href="register.html">Sign up</a></li> </ul>                 </div> </div> </nav> </header> <div id="hero" class="static-header  light clearfix"> <div class="text-heading"> <h1 data-animation="bounceInDown" data-delay="0"><span class="highlight">Improve it</span> with native speakers around the world!</h1> <ziggeo> </ziggeo> <div class="form-group submit-wrap"> <input type="hidden" name="small-form"/> <form method = "POST"> <button type="submit" class="btn btn-primary btn-md" >Start the convesation NOW!</button> </form> </div> <p  data-delay="500">Improving another language, please suggest it in the space below.</p> </div> </section>  <div class="back-to-top"><i class="fa fa-angle-up fa-3x"></i></div>     <script type="text/javascript" src="assets/js/jquery-2.1.0.min.js?ver=1"></script>  <script type="text/javascript" src="assets/js/bootstrap.min.js"></script> <script type="text/javascript" src="assets/js/scripts.js"></script></body></html>';return out;
}var itself=home, _encodeHTML=(function (doNotSkipEncoded) {
		var encodeHTMLRules = { "&": "&#38;", "<": "&#60;", ">": "&#62;", '"': "&#34;", "'": "&#39;", "/": "&#47;" },
			matchHTML = doNotSkipEncoded ? /[&<>"'\/]/g : /&(?!#?\w+;)|<|>|"|'|\//g;
		return function(code) {
			return code ? code.toString().replace(matchHTML, function(m) {return encodeHTMLRules[m] || m;}) : "";
		};
	}());if(typeof module!=='undefined' && module.exports) module.exports=itself;else if(typeof define==='function')define(function(){return itself;});else {_page.render=_page.render||{};_page.render['home']=itself;}}());